algoritmo "exercício"
// Função :
// Autor :
// Data : 01/09/2021
// Seção de Declarações 
var
   raio, altura, volume: real
   base, contador, resultado: real
   expoente: inteiro
   area: real
   
inicio
escreval("Informe o valor do raio")
leia(raio)
escreval("Informe o valor da altura")
leia(altura)

volume <- pi * raio^2 * altura
escreval("O valor do volume do cilindrto é de: ",volume:6:2, " m3")




 
fimalgoritmo
