algoritmo "exercício"
// Função :
// Autor :
// Data : 01/09/2021
// Seção de Declarações 
var
   base, altura, profundidade: real
   volume: real
inicio
escreval ("Digite o valor da base: ")
leia (base)
escreval ("Digite o valor da altura: ")
leia (altura)
escreval ("Digite o valor da profundidade: ")
leia (profundidade)
volume <- base * altura * profundidade
escreval(" O volume do Paralelepípedo é de:  ", volume:6:2, " m3")





 
fimalgoritmo
