algoritmo "semnome"
// Função :
// Autor :
// Data : 16/10/2021
// Seção de Declarações 
var
i, n2, n1, res: inteiro
inicio
// Seção de Comandos

Escreva ("Escreva o valor do primeiro número: ")
leia(n1)
Escreva ("Escreva o valor do segundo número: ")
leia(n2)


para i de 1 ate n2 passo 1 faca
res <- res + n1
fimpara

Escreva("A soma progressiva dos números ",n1," e ",n2," é de ",res)


 
fimalgoritmo
